### ISSUE TITLE
打开包含大量文件的目录，插件会coredump

### ISSUE THREAD

**Issue by mwdxr200201** [Tencent/LuaPanda#160]
通过ssh remote打开一个包含大量文件的工程目录，插件会coredump

是不是插件分析的文件太多，造成oom了，如果是这个原因能否限定文件分析的目录？

output窗口输出了以下信息：
<--- Last few GCs --->

[17929:0x5ccdd70]    77604 ms: Mark-sweep (reduce) 4074.1 (4143.0) -> 4073.7 (4143.7) MB, 8053.9 / 0.0 ms  (average mu = 0.136, current mu = 0.001) allocation failure scavenge might not succeed
[17929:0x5ccdd70]    85715 ms: Mark-sweep (reduce) 4074.8 (4143.7) -> 4074.5 (4144.5) MB, 8108.1 / 0.0 ms  (average mu = 0.071, current mu = 0.000) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00e10 node::Abort() [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 2: 0xa1823b node::FatalError(char const*, char const*) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 3: 0xcee09e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 4: 0xcee417 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 5: 0xea65d5  [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 6: 0xeb5cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 7: 0xeb89ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 8: 0xe79dda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
 9: 0x11f33d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
10: 0x15e7cf9  [/home/xxx/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/node]
[Info  - 上午10:14:24] Connection to server got closed. Server will restart.
[Error - 上午10:14:24] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
(node:18569) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/xxx/.vscode-server/extensions/stuartwang.luapanda-3.2.0/node_modules/antlr4/package.json' of 'src/antlr4/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:18569) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(node:18569) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
LuaAnalyzer init success!
文件Cache刷新完毕，共计104410个文件， 其中3195个lua类型文件

**Desktop (please complete the following information):**
 - debian9
 - Visual Studio Version 1.7
 - luapanda 3.2

**Comment by stuartwang** [comment]
我看了下堆栈，应该是文件比较多导致代码符号分析部分挂了。 可以这样把符号分析关掉看还是否会报错
![image](https://user-images.githubusercontent.com/16960038/234451813-2a2b27f9-2bb1-4db2-9d44-15f6b305e677.png)

**Comment by mwdxr200201** [comment]
关闭后不会coredump了
问下，后续可以指定分析路径吗

**Comment by stuartwang** [comment]
我最近重新看了下工程，准备做一些修复，暂时还不打算开发新功能哈。
