### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by huangchaoqun** [Tencent/LuaPanda#54]
**Connection to server got closed. Server will not be restarted.**
文件Cache刷新完毕，共计606个文件， 其中604个lua类型文件
c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at next (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\path-reader\lib\readfiles.js:83:23)
    at c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\path-reader\lib\readfiles.js:98:74
    at FSReqCallback.oncomplete (fs.js:166:5)
[Info  - 上午10:00:17] Connection to server got closed. Server will restart.
[Error - 上午10:00:17] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.<anonymous> (c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
文件Cache刷新完毕，共计606个文件， 其中604个lua类型文件
TypeError: uri.match is not a function
TypeError: uri.match is not a function

c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),
abort(TypeError: uri.match is not a function). Build with -s ASSERTIONS=1 for more info.
[Info  - 上午10:00:39] Connection to server got closed. Server will restart.
文件Cache刷新完毕，共计606个文件， 其中604个lua类型文件
TypeError: uri.match is not a function
TypeError: uri.match is not a function

c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),
abort(TypeError: uri.match is not a function). Build with -s ASSERTIONS=1 for more info.
[Info  - 上午10:01:00] Connection to server got closed. Server will restart.
文件Cache刷新完毕，共计606个文件， 其中604个lua类型文件
TypeError: uri.match is not a function
TypeError: uri.match is not a function

c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),
abort(TypeError: uri.match is not a function). Build with -s ASSERTIONS=1 for more info.
[Info  - 上午10:01:15] Connection to server got closed. Server will restart.
文件Cache刷新完毕，共计606个文件， 其中604个lua类型文件
TypeError: uri.match is not a function
TypeError: uri.match is not a function

c:\Users\tcuser\.vscode\extensions\stuartwang.luapanda-3.1.0\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),
abort(TypeError: uri.match is not a function). Build with -s ASSERTIONS=1 for more info.
[Error - 上午10:01:31] Connection to server got closed. Server will not be restarted.

**Comment by stuartwang** [comment]
Thanks for the issue. We already check code and locate the error. We will take some time to reproduce this error, understand why the problem occurs, so as to fix it.

**Comment by CUTEQWQ** [comment]
LuaAnalyzer init success!
文件Cache刷新完毕，共计267个文件， 其中266个lua类型文件
TypeError: Cannot set property size of #<Map> which has only a getter

我这边有同样的问题。。
